#!/bin/sh
#
# Insert I2C Module 
#

case "$1" in
    start)
        echo "Adding I2C modules"
        modprobe i2c-bcm2835
        modprobe i2c-dev
    ;;
    stop)
        echo "Removing I2C modules"
        rmmod i2c-bcm2835
        rmmod i2c-dev
    ;;
    restart|reload)
        "$0" stop
        "$0" start
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0