#!/bin/sh
#
# Start the server....
#

case "$1" in
  start)
	echo "Starting Pomodoro Server: "
    gunicorn -w 1 'pomodoro:create_app()' -b 0.0.0.0:5000 --daemon
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	echo "Stopping Pomodoro Server: "
    killall gunicorn
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?